### ISSUE TITLE
I can not enable the addon gives an error

### ISSUE THREAD

**Issue by World4567** [TheDuckCow/MCprep#218]
When turned on, it gives:

Traceback (most recent call last):
  File "E:\Games\steamapps\common\Blender\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\Владислав\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MCprep_addon\__init__.py", line 61, in register
    load_modules.register(bl_info)
  File "C:\Users\Владислав\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MCprep_addon\load_modules.py", line 152, in register
    tracking.register(bl_info)
  File "C:\Users\Владислав\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MCprep_addon\tracking.py", line 965, in register
    system = bpy.context.user_preferences.system
ValueError: register_class(...): already registered as a subclass 'TRACK_OT_toggle_enable_tracking'

**Comment by TheDuckCow** [comment]
Hello,

Please try restarting blender, and if that does not work, try removing MCprep (not just untick, but actually expand and press the remove button), then close blender, and then re-opening and installing fresh. Let me know if that doesn't work!

**Comment by World4567** [comment]
Thanks for the help
