### ISSUE TITLE
when i try to use pickaxe give me this Error

### ISSUE THREAD

**Issue by aaadell** [TheDuckCow/MCprep#63]
Traceback (most recent call last):
  File "C:\Users\zoomb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MCprep_addon\tracking.py", line 735, in wrapper
    err = Tracker.remove_indentifiable_information(err)
  File "C:\Users\zoomb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MCprep_addon\tracking.py", line 374, in remove_indentifiable_information
    report)
  File "D:\blender-2.79.0-git.a8b8da55672-windows64\2.79\python\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "D:\blender-2.79.0-git.a8b8da55672-windows64\2.79\python\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "D:\blender-2.79.0-git.a8b8da55672-windows64\2.79\python\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "D:\blender-2.79.0-git.a8b8da55672-windows64\2.79\python\lib\sre_parse.py", line 970, in parse_template
    this = sget()
  File "D:\blender-2.79.0-git.a8b8da55672-windows64\2.79\python\lib\sre_parse.py", line 256, in get
    self.__next()
  File "D:\blender-2.79.0-git.a8b8da55672-windows64\2.79\python\lib\sre_parse.py", line 246, in __next
    self.string, len(self.string) - 1) from None
re.error: bad escape (end of pattern) at position 18

location: <unknown location>:-1

**Comment by aaadell** [comment]
in the same project i can't import pickaxe 

but when i tried in new project its work fine

**Comment by TheDuckCow** [comment]
Marking this as fixed, please try out the latest 3.2.0 release and let me know if you run into other issues!
